[SERVICE]
    Flush             5
    Log_Level         info
    Daemon            off
    Parsers_File      parsers.conf

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    Tag               docker.forward

[FILTER]
    Name              record_modifier
    Match             *
    Record            source      fluent-bit
    Record            environment development

[FILTER]
    Name              grep
    Match             *
    Exclude           log ^$

[OUTPUT]
    Name              es
    Match             *
    Host              elasticsearch
    Port              9200
    Index             logs
    Suppress_Type_Name On
    tls               Off
    tls.verify        Off
    Retry_Limit       5

[OUTPUT]
    Name              stdout
    Match             *
    Format            json_lines
